name: Build debug and export APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Build debug APK
      run: bash ./gradlew assembleDebug
    - name: Upload generated APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
